"""
gradio_app.py — chat interface for Triage, mounted on the existing FastAPI app.

    Gradio UI  ->  /
    JSON API   ->  /chat, /score, /health, /sync/*
    Swagger    ->  /docs

Both surfaces share one process, so the models load once and serve both.

WHY THE CONFIDENCE BADGE IS PART OF THE UI
------------------------------------------
The contribution of this project is not that it answers questions — every RAG
bot does that. It is that it knows when it CANNOT answer, and skips the
generation call entirely when retrieval failed. If the interface hides that,
the demo looks like any other chatbot.

So every answer carries its band, the retrieval route that produced it, and
whether the LLM was called at all. A refusal reads:

    LOW 0.08 · plain search · LLM skipped — no cost incurred

which is the whole thesis in one line.

Run locally:
    python gradio_app.py
"""

import asyncio

import gradio as gr

from app import app as fastapi_app

BAND_STYLE = {
    "high": ("#1a7f37", "HIGH"),
    "medium": ("#9a6700", "MEDIUM"),
    "low": ("#b42318", "LOW"),
}

EMPTY_DB_NOTICE = """
### Database is empty

Triage has no data to search yet. Open the **Data** tab and run a sync — it
scrapes the Amrita Bengaluru admissions pages and builds the vector store.

This takes roughly 10–15 minutes: 26 seed pages in pass 1, then a few hundred
faculty profile pages discovered from the faculty card grids in pass 2.
"""


def _badge(result):
    """One line summarising how the answer was produced."""
    band = result.get("band", "low")
    colour, label = BAND_STYLE.get(band, BAND_STYLE["low"])
    confidence = result.get("confidence") or 0.0
    route = result.get("route") or "plain search"

    if not result.get("llm_called"):
        cost = "LLM skipped — no cost incurred"
    else:
        model = (result.get("model") or "").split("/")[-1]
        cost = f"generated by {model}" if model else "LLM called"

    return (
        f"<div style='font-size:0.85em;color:#666;margin-top:8px'>"
        f"<span style='color:{colour};font-weight:600'>{label} {confidence}</span>"
        f" &nbsp;·&nbsp; {route} &nbsp;·&nbsp; {cost}</div>"
    )


def _sources(result):
    urls = result.get("sources") or []
    if not urls:
        return ""
    lines = "\n".join(f"- [{u.split('//')[-1][:70]}]({u})" for u in urls)
    return f"\n\n**Sources**\n{lines}"


def respond(message, history):
    """Gradio chat callback. Returns the updated history."""
    from store import count

    if count() == 0:
        history.append({"role": "user", "content": message})
        history.append({"role": "assistant", "content": EMPTY_DB_NOTICE})
        return history, ""

    from generator import answer_query

    try:
        result = asyncio.run(answer_query(message))
    except Exception as exc:
        history.append({"role": "user", "content": message})
        history.append({"role": "assistant",
                        "content": f"Something went wrong: `{exc}`"})
        return history, ""

    reply = result["answer"] + _sources(result) + _badge(result)
    history.append({"role": "user", "content": message})
    history.append({"role": "assistant", "content": reply})
    return history, ""


def inspect(message):
    """Retrieval + confidence only. No LLM call, so this is free to run."""
    from confidence import score_query
    from store import count

    if not message.strip():
        return "Type a question first."
    if count() == 0:
        return EMPTY_DB_NOTICE

    result = asyncio.run(score_query(message))
    d = result.get("retrieval_details", {})

    lines = [
        f"**{result['band'].upper()} {result['final_confidence']}** &nbsp;·&nbsp; "
        f"route: `{result.get('route') or 'plain search'}` &nbsp;·&nbsp; "
        f"mode: `{result['generator_mode']}`",
        "",
        f"- `abs_signal` **{d.get('abs_signal')}** — is the top chunk strong on its own?",
    ]
    if d.get("filtered_pool"):
        lines.append("- `sep_signal` **n/a** — filtered pool, no rejected set to measure")
        lines.append(f"- `set_confidence` **{d.get('set_confidence')}** = max(abs, rank)")
    else:
        lines.append(f"- `sep_signal` **{d.get('sep_signal')}** — does it tower over this query's noise floor?")
        lines.append(f"- `set_confidence` **{d.get('set_confidence')}** = max(abs, sep)")
    lines.append(f"- `rank_confidence` **{d.get('rank_confidence')}** — do we know *which* chunk?")
    lines.append(f"- `agreement` **{d.get('ensemble_agreement')}** — 5-model category vote")
    lines.append("\n**Retrieved chunks**\n")

    for i, c in enumerate(result.get("chunks", []), start=1):
        preview = " ".join(c["content"].split())[:180]
        lines.append(f"{i}. `{c['rerank_score']:.4f}` — {c['source_url']}  \n   {preview}…")

    return "\n".join(lines)


def data_status():
    from scheduler import STATUS, next_run_time
    from store import count

    total = count()
    rows = [f"**Chunks in vector store:** {total or 0}"]

    if total == 0:
        rows.append("\nThe database is empty. Run a sync to populate it.")
    if STATUS["last_run"]:
        rows.append(f"\n**Last sync:** {STATUS['last_run']} "
                    f"({STATUS['last_status']}, {STATUS['last_duration_seconds']}s)")
    if STATUS["last_error"]:
        rows.append(f"\n**Last error:** `{STATUS['last_error']}`")

    scheduler = getattr(fastapi_app.state, "scheduler", None)
    upcoming = next_run_time(scheduler)
    if upcoming:
        rows.append(f"\n**Next scheduled sync:** {upcoming}")

    health = STATUS.get("health")
    if health:
        rows.append(f"\n**Departments with their own head:** "
                    f"{health['departments_with_heads'] or 'none'}")
        for warning in health["warnings"]:
            rows.append(f"\n⚠️ {warning}")

    return "\n".join(rows)


def trigger_sync():
    """Blocking on purpose — the user asked for it and wants to see the result."""
    from scheduler import run_sync

    result = run_sync(triggered_by="gradio")
    if result["status"] == "busy":
        return "A sync is already running. Check back in a few minutes."
    if result["status"] == "failed":
        return (f"Sync failed: `{result['detail']}`\n\n"
                f"If this mentions Playwright or a browser, Crawl4AI could not "
                f"launch a headless browser in this container.")
    return f"Sync complete — {result['chunks']} chunks in the vector store.\n\n" \
           + data_status()


EXAMPLES = [
    "what is the fee for btech ECE",
    "who is the HOD of ECE",
    "who is the chairman of mechanical engineering",
    "what is the eligibility for btech admission",
    "what are the hostel facilities in Bengaluru campus",
    "what is the hostel fee in Coimbatore campus",
]

# Gradio 6 moved `theme` out of the Blocks constructor and into launch().
# Since this app is mounted on FastAPI rather than launched, the theme is set
# on mount_gradio_app at the bottom of the file instead.
with gr.Blocks(title="Triage") as demo:
    gr.Markdown(
        "# Triage\n"
        "Confidence- and cost-aware RAG for **Amrita Vishwa Vidyapeetham, "
        "Bengaluru** \n\n"
        "Every answer shows how confident the system is, which retrieval "
        "strategy produced it, and whether the generation model was called at "
        "all — low-confidence queries are refused *without* spending on "
        "generation."
    )

    with gr.Tab("Chat"):
        # Gradio 6 dropped the `type` argument — the messages format
        # ({"role": ..., "content": ...}) is now the only one, which is what
        # respond() already returns.
        chatbot = gr.Chatbot(height=460, show_label=False)
        with gr.Row():
            box = gr.Textbox(placeholder="Ask about fees, faculty, curriculum, "
                                         "hostel…", show_label=False, scale=9)
            send = gr.Button("Send", variant="primary", scale=1)
        gr.Examples(EXAMPLES, inputs=box, label="Try one")

        send.click(respond, [box, chatbot], [chatbot, box])
        box.submit(respond, [box, chatbot], [chatbot, box])

    with gr.Tab("Inspect"):
        gr.Markdown(
            "Retrieval and confidence only — **no generation call**, so this "
            "costs nothing to run. Useful for seeing *why* a query scored the "
            "way it did."
        )
        inspect_box = gr.Textbox(label="Query")
        inspect_btn = gr.Button("Score", variant="primary")
        inspect_out = gr.Markdown()
        inspect_btn.click(inspect, inspect_box, inspect_out)

    with gr.Tab("Data"):
        gr.Markdown(
            "The vector store is built by scraping the Amrita Bengaluru pages. "
            "A full sync takes roughly 10–15 minutes and runs automatically "
            "every Sunday at 03:00 IST."
        )
        status_out = gr.Markdown(value="Click refresh to load status.")
        with gr.Row():
            refresh_btn = gr.Button("Refresh status")
            sync_btn = gr.Button("Run sync now", variant="stop")
        refresh_btn.click(data_status, None, status_out)
        sync_btn.click(trigger_sync, None, status_out)

    gr.Markdown(
        "<div style='text-align:center;color:#888;font-size:0.8em;margin-top:16px'>"
        "JSON API at <code>/chat</code> and <code>/score</code> · "
        "docs at <a href='/docs'>/docs</a></div>"
    )

# Gradio at /, FastAPI keeps its own routes.
app = gr.mount_gradio_app(fastapi_app, demo, path="/")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)